/* Javascript output generated by archetype 1.4.1 */

/* Utils functions */

export const mk_int = (v) => {
  return { int: v.toString() }
}
export const mk_string = (v) => {
  return { string: v }
}
export const mk_bytes = (v) => {
  return { bytes: v.toString() }
}
export const mk_some = (v) => {
  return { prim: 'Some', args: [v] }
}
export const mk_none = () => {
  return { prim: 'None' }
}
export const mk_rational = (n, d) => {
  return { prim: 'Pair', args: [{ int: n.toString() }, { int: d.toString() }] }
}

/* Code */

export const code = [
  {
    prim: 'storage',
    args: [
      {
        prim: 'pair',
        args: [
          { prim: 'nat', annots: ['%par'] },
          { prim: 'nat', annots: ['%res'] },
          { prim: 'nat', annots: ['%ser'] },
        ],
      },
    ],
  },
  { prim: 'parameter', args: [{ prim: 'nat', annots: ['%exec'] }] },
  {
    prim: 'code',
    args: [
      [
        { prim: 'UNPAIR' },
        {
          prim: 'DIP',
          args: [{ int: '1' }, [{ prim: 'UNPAIR', args: [{ int: '3' }] }]],
        },
        { prim: 'DUP' },
        {
          prim: 'DIP',
          args: [
            { int: '1' },
            [
              { prim: 'DIG', args: [{ int: '2' }] },
              { prim: 'DROP', args: [{ int: '1' }] },
            ],
          ],
        },
        { prim: 'DUG', args: [{ int: '2' }] },
        { prim: 'DUP', args: [{ int: '2' }] },
        {
          prim: 'DIP',
          args: [
            { int: '1' },
            [
              { prim: 'DIG', args: [{ int: '3' }] },
              { prim: 'DROP', args: [{ int: '1' }] },
            ],
          ],
        },
        { prim: 'DUG', args: [{ int: '3' }] },
        { prim: 'DROP', args: [{ int: '1' }] },
        { prim: 'PAIR', args: [{ int: '3' }] },
        { prim: 'NIL', args: [{ prim: 'operation' }] },
        { prim: 'PAIR' },
      ],
    ],
  },
]

export const getStorage = ({ par }) => {
  return {
    prim: 'Pair',
    args: [{ int: par.toString() }, { int: '0' }, { int: '1' }],
  }
}
